pipeline{
    agent any
   
    tools { 
        maven 'maven'
        jdk 'jdk'
    }
        stages{
            stage('Git-Checkout ')
            {
                steps{
                    script{
                        FAILED_STAGE=env.STAGE_NAME
                     git 'https://github.com/sravanin15/CalculatorRepo.git'
                    
                    }
                }
            }
             stage('Validate')
        {
            steps{
                 script{
                FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f Calculator clean validate'
                 }
            }
        }
        stage('Compile')
        {
            steps{
                script{
                FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f  Calculator compile'
                }
            }
        }
        stage('sonar analysis'){
            steps{
                script{
                FAILED_STAGE=env.STAGE_NAME
                withSonarQubeEnv('sonarserver'){
                    withMaven(maven:'maven'){
                        bat 'mvn -f Calculator sonar:sonar'
                    }
                }
                }
            }

        }
        stage("Quality gate") {
            steps {
                script{
                FAILED_STAGE=env.STAGE_NAME
                waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Test')
        {
            steps{
                script{
                FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f  Calculator test'
                }
            }
        }
        stage('Package')
        {
            steps{
                script{
                FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f  Calculator package'
                }
            }
        }
        stage('Verify')
        {
            steps{
                 script{
                FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f Calculator verify'
                 }
            }
        }
        stage('Install')
        {
            steps{
                 script{
                FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f  Calculator install '
                 }
            }
        }
       stage('Collect-Artifactory')
    {
      steps{
         script{
          FAILED_STAGE=env.STAGE_NAME
        archiveArtifacts artifacts:'Calculator/target/*.jar',followSymlinks:false
          }
      }
    }   
    stage('Deploy-To-Artifactory')
    {
      steps{
         script{
          FAILED_STAGE=env.STAGE_NAME
        rtUpload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "Calculator/target/*.jar",
              "target": "art-doc-dev-loc"
            }
         ]
    }''',
          
)
          }
  }
}   
            
           
        }
    post {  
         always {  
             echo 'This will always run'  
         }  
         success {  
             echo 'This will run only if successful'  
         }  
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br>Build Stage: ${FAILED_STAGE} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sravaninuthanapati15@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sravaninuthanapati15@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if  the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline has changed'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }      
}
